name: Node.js Build

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.2' # Replace with your desired Node.js version
      - name: Install esbuild, jest & pkg
        run: npm install --save-exact esbuild && npm i jest --save-dev && npm i -g pkg
      - name: Install Dependencies
        run: npm ci
      - name: test
        run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        run: npm run build
      - name: upload
        run: gh release create wip-${{ github.sha }} ./dist/* --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
