name: Node.js Build

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Replace with your desired Node.js version
          
      - name: Install pkg
        run: npm i -g pkg

      - name: Install esbuild
        run: npm install --save-exact esbuild
        
      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: upload
        run: gh release create wip-${{ github.sha }} ./dist/* --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
